package GUI;

import javax.swing.JTextField;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nikola
 */
public class ControlsPanel extends javax.swing.JPanel implements SceneDelegate{

    private ControlsDelegate controlsDelegate;
    
    public void setControlsDelegate(ControlsDelegate pDelegate){
        this.controlsDelegate= pDelegate;
    }
    
    public ControlsDelegate getControlsDelegate(){
        return controlsDelegate;
    }
    
    /**
     * Creates new form ControlsPanel
     */
    public ControlsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        xRotationField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        yRotationField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        zRotationField = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("X:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel1, gridBagConstraints);

        xRotationField.setText("0");
        xRotationField.setMinimumSize(new java.awt.Dimension(30, 20));
        xRotationField.setPreferredSize(new java.awt.Dimension(40, 20));
        xRotationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xRotationFieldActionPerformed(evt);
            }
        });
        xRotationField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                xRotationFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(xRotationField, gridBagConstraints);

        jLabel2.setText("Y:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel2, gridBagConstraints);

        yRotationField.setText("0");
        yRotationField.setMinimumSize(new java.awt.Dimension(30, 20));
        yRotationField.setPreferredSize(new java.awt.Dimension(40, 20));
        yRotationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yRotationFieldActionPerformed(evt);
            }
        });
        yRotationField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                yRotationFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(yRotationField, gridBagConstraints);

        jLabel3.setText("Z:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel3, gridBagConstraints);

        zRotationField.setText("0");
        zRotationField.setMinimumSize(new java.awt.Dimension(30, 20));
        zRotationField.setPreferredSize(new java.awt.Dimension(40, 20));
        zRotationField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                zRotationFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(zRotationField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void xRotationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xRotationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xRotationFieldActionPerformed

    private void yRotationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yRotationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yRotationFieldActionPerformed

    private void zRotationFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zRotationFieldKeyReleased
        updateRotationData();
    }//GEN-LAST:event_zRotationFieldKeyReleased

    private void yRotationFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yRotationFieldKeyReleased
        updateRotationData();
    }//GEN-LAST:event_yRotationFieldKeyReleased

    private void xRotationFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xRotationFieldKeyReleased
        updateRotationData();
    }//GEN-LAST:event_xRotationFieldKeyReleased

    private void updateRotationData(){
        if(getControlsDelegate()!=null){
            float x= valueFromField(xRotationField);
            float y= valueFromField(yRotationField);
            float z= valueFromField(zRotationField);
            getControlsDelegate().didChangeRotation(x, y, z);
        }
    }
    
    public float valueFromField(JTextField pField){
        float value= 0f;
        try{
            value= Float.parseFloat(pField.getText());
        }catch(NumberFormatException ex){
            value= 0f;
        }
        
        return value;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField xRotationField;
    private javax.swing.JTextField yRotationField;
    private javax.swing.JTextField zRotationField;
    // End of variables declaration//GEN-END:variables

    public void rotationDidChange(float x, float y, float z) {
        float xAngle= angle(x);
        float yAngle= angle(y);
        float zAngle= angle(z);
        
        setAngleValues(xAngle, yAngle, zAngle);
    }
    
    private void setAngleValues(float x, float y, float z){
        xRotationField.setText(String.valueOf(x));
        yRotationField.setText(String.valueOf(y));
        zRotationField.setText(String.valueOf(z));
    }
    
    private float angle(float pAngle){
        if(radians)
            return pAngle;
        
        return (float) Math.toDegrees(pAngle);
    }
    
    private boolean radians;
}
